name: Build and Deploy to Plesk FTP

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Adım 1: Repository'yi checkout et
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Adım 2: .NET 9 SDK'sını kur
      - name: Setup .NET 9 SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x' # .NET 9 kullanıyorsunuz

      # Adım 3: Bağımlılıkları restore et
      - name: Restore dependencies
        run: dotnet restore ./yummyApp.sln

      # Adım 4: API projesini build et
      - name: Build API
        run: dotnet build ./yummyApp.Api/yummyApp.Api.csproj -c Release --no-restore

      # Adım 5: API projesini publish et
      - name: Publish API
        run: dotnet publish ./yummyApp.Api/yummyApp.Api.csproj -c Release -r win-x64 --self-contained false -o publish/api

      # Adım 6: Web projesini build et
      - name: Build Web
        run: dotnet build ./yummyApp.Web/yummyApp.Web.csproj -c Release --no-restore

      # Adım 7: Web projesini publish et
      - name: Publish Web
        run: dotnet publish ./yummyApp.Web/yummyApp.Web.csproj -c Release -r win-x64 --self-contained false -o publish/web

      # Adım 8: API'yi Plesk'e FTP ile deploy et
      - name: Deploy API to Plesk via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./publish/api/
          server-dir: /httpdocs/api/

      # Adım 9: Web'i Plesk'e FTP ile deploy et
      - name: Deploy Web to Plesk via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./publish/web/
          server-dir: /httpdocs/
