name: Deploy to Plesk FTP

on:
  push:
    branches:
      - master  # veya hangi branch'ı kullanıyorsan

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'  # Kendi .NET sürümüne göre güncelle

      - name: Restore Dependencies
        run: dotnet restore ./yummyApp.sln

      - name: Build API Project
        run: dotnet build ./yummyApp.Api/yummyApp.Api.csproj -c Release --no-restore

      - name: Build Web Project
        run: dotnet build ./yummyApp.Web/yummyApp.Web.csproj -c Release --no-restore

      - name: Publish API Project
        run: dotnet publish ./yummyApp.Api/yummyApp.Api.csproj -c Release -r win-x64 --self-contained false -o publish/api

      - name: Publish Web Project
        run: dotnet publish ./yummyApp.Web/yummyApp.Web.csproj -c Release -r win-x64 --self-contained false -o publish/web

      - name: Upload API to FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./publish/api/
          server-dir: /httpdocs/api/

      - name: Upload Web to FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./publish/web/
          server-dir: /httpdocs/web/
